DROP TABLE MEMBER1 PURGE;
CREATE TABLE MEMBER1(
  ID VARCHAR2(12) PRIMARY KEY,
  PASSWORD VARCHAR2(12) NOT NULL,
  NAME VARCHAR2(12) NOT NULL,
  REG_DATE DATE NOT NULL
);

CREATE TABLE MEMBER2(
  ID   VARCHAR2(12) PRIMARY KEY,
  PASSWD VARCHAR2(12) NOT NULL,
  NAME VARCHAR2(20) NOT NULL,
  ADDREDD VARCHAR2(50),
  TEL VARCHAR2(20) NOT NULL,
  REG_DATE DATE
);


